FROM openjdk:17-jdk-alpine

# Copia el archivo JAR generado de tu proyecto a la imagen
#COPY /root/reserve_spaces/backend_spaces.jar /app/
COPY /cdn_images/build/libs/cdn-files-0.0.1.jar /app/

# Define el directorio de trabajo dentro de la imagen
WORKDIR /app

# Expone el puerto en el que tu aplicación Spring Boot escucha
EXPOSE 9000

ENTRYPOINT ["java", "-jar", "cdn-files-0.0.1.jar"]
