version: '3.3'

services:
  mysql:
    image: mysql:8.3.0
    environment:
      - MYSQL_DATABASE=pets_location_db
      - MYSQL_ROOT_PASSWORD=admin123
#      - MYSQL_TCP_PORT=3307
#      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - pets-location-network

  pets-location_service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/pets_location_db
    depends_on:
      - mysql
    networks:
      - pets-location-network
  
  frontend:
    build:
      context: .
      dockerfile: DockerfileFrontend
    ports:
      - 4200:80         # Mapea puerto 80 del contenedor al 4200 local
    depends_on:
      - pets-location_service
    networks:
      - pets-location-network

#le pasamos el servicio de mysql como host en los environments
networks:
  pets-location-network:
    driver: bridge