version: '3.3'

services:
  mysql:
    image: mysql:8.3.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - pets-location-network
    restart: unless-stopped

  pets-location_service:
    build: 
      context: .
      dockerfile: Dockerfile.pets
    ports:
      - 9090:9090
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      - spring.datasource.username=${MYSQL_USER}
      - spring.datasource.password=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - pets-location-network
    restart: unless-stopped
  
  cdn-files_service:
    build: 
      context: .
      dockerfile: Dockerfile.cdn
    ports:
      - 9000:9000
    networks:
      - pets-location-network
    restart: unless-stopped

networks:
  pets-location-network:
    driver: bridge
