name: pets_location_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+2

  image_picker: ^0.8.7+5

  mime: ^1.0.4
  http_parser: ^4.0.2
  intl: ^0.18.1 #dateformat

  #User Geolocator
  geolocator: ^11.0.0

  #Google Sign in
  firebase_core: ^3.3.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1

  # WebSockets
  web_socket_channel: ^2.4.0
  stomp_dart_client: ^0.4.4

  # Íconos de Cupertino
  cupertino_icons: ^1.0.8

  # HTTP
  dio: ^5.4.0
  http: ^1.2.1

  # Almacenamiento seguro (para JWT)
  flutter_secure_storage: ^9.0.0

  # Navegación avanzada
  go_router: ^13.0.0

  # Gestión de estado reactivo
  flutter_riverpod: ^2.6.1

  # JSON
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Generadores de código para JSON
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cat.png
    - assets/images/pet_location.png
    - assets/icons/google-logo.png
    - assets/images/homepage.png
    - assets/icons/missing_pet.png
    - assets/icons/searching_home.png
    - assets/icons/pet_found.png
    - assets/icons/pet_store.png
    - assets/icons/pet_events.png
    - assets/icons/pet_advices.png
    - assets/icons/pet_health.png
    - assets/icons/award_pet.png
    - assets/icons/pet_service.png
    - assets/icons/pet_happy_stories.png
    - assets/icons/pet_alert.png