// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo8h9xyKfb9vHJTq2XquTtKtI3sFTYUvw',
    appId: '1:111778708935:web:4e337fc25ddd6e60c52de2',
    messagingSenderId: '111778708935',
    projectId: 'geo-pets-27b8b',
    authDomain: 'geo-pets-27b8b.firebaseapp.com',
    storageBucket: 'geo-pets-27b8b.firebasestorage.app',
    measurementId: 'G-MHGRGDWBMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4aAt4Dd_CwHWo21UEINMBNotm5jF3qdk',
    appId: '1:111778708935:android:d22bd9fbffebbe6bc52de2',
    messagingSenderId: '111778708935',
    projectId: 'geo-pets-27b8b',
    storageBucket: 'geo-pets-27b8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8C7wPolkvrExE9yvgjTcpt35ao8XHGEs',
    appId: '1:111778708935:ios:1df33ebfab58881ac52de2',
    messagingSenderId: '111778708935',
    projectId: 'geo-pets-27b8b',
    storageBucket: 'geo-pets-27b8b.firebasestorage.app',
    androidClientId: '111778708935-d2289spalvqt2v216bsm376uvusgbmbf.apps.googleusercontent.com',
    iosClientId: '111778708935-f6u3e5pq69g08jokfl4jlvfff0c0bhfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.petsLocationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8C7wPolkvrExE9yvgjTcpt35ao8XHGEs',
    appId: '1:111778708935:ios:1df33ebfab58881ac52de2',
    messagingSenderId: '111778708935',
    projectId: 'geo-pets-27b8b',
    storageBucket: 'geo-pets-27b8b.firebasestorage.app',
    androidClientId: '111778708935-d2289spalvqt2v216bsm376uvusgbmbf.apps.googleusercontent.com',
    iosClientId: '111778708935-f6u3e5pq69g08jokfl4jlvfff0c0bhfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.petsLocationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo8h9xyKfb9vHJTq2XquTtKtI3sFTYUvw',
    appId: '1:111778708935:web:6ea7367febd7db67c52de2',
    messagingSenderId: '111778708935',
    projectId: 'geo-pets-27b8b',
    authDomain: 'geo-pets-27b8b.firebaseapp.com',
    storageBucket: 'geo-pets-27b8b.firebasestorage.app',
    measurementId: 'G-QMF1XEL8VB',
  );
}
